### ISSUE TITLE
Incompatible with lwjgl3ify 1.5.1

### ISSUE THREAD

**Issue by sousuke0422** [makamys/CoreTweaks#18]
I updated lwjgl3ify from 1.4.x and it stopped working

log: https://mclo.gs/8ihTP0j

<img width="194" alt="image" src="https://github.com/makamys/CoreTweaks/assets/33174568/9a72c538-ba8c-43f0-b957-e2fe89a8d485">

**Comment by SilearFlare** [comment]
To be fair, lwjgl3ify is sort of a very heavy handed hack that breaks compat with most mods. Breakages are the norm, more than the exception.

**Comment by charagarlnad** [comment]
If you disable `jar_discoverer_cache` in the CoreTweaks config, the crash goes away.

**Comment by SilearFlare** [comment]
Oh hey, good call.

**Comment by makamys** [comment]
Pretty sure this was just an issue on my side, I initialized the jar discoverer cache really early, and it caused some other classes to get loaded earlier than normal, which broke LWJGL3ify's mixins that happened to be targeting those classes.

**Comment by SilearFlare** [comment]
_`**HE'S BACK**`_
Cool, thanks.
Any chance it might ever be possible to get smart moving to not crash with it eventually or it's one of those really up in the air things where both mods just change too much stuff to actually get them to work together properly?

**Comment by makamys** [comment]
IIRC that was a pretty simple issue on SM's side that I just never bothered to fix, will have a look at it later.
