### ISSUE TITLE
Fix BoP's leaves having 'holes' in them.

### ISSUE THREAD

**Issue by MagmaBro123** [makamys/CoreTweaks#21]
Title. Currently using the Modernity resource pack, but this also happens without any other mods or resource packs.

![2023-10-29_15 18 27](https://github.com/makamys/CoreTweaks/assets/51277766/40f8fa07-ae86-4ed5-b3fc-b1ac8d60349a)

**Comment by makamys** [comment]
This is out of scope for CoreTweaks, this mod is about tweaking vanilla/Forge (the "core" of the game) and occasionally other mods with the same goal (e.g. OptiFine), not content mods. (To be fair, I don't think I've made this clear anywhere.) In fact, I don't even have the machinery set up for mixing into non-coremods.

BugTorch/Hodgepodge/ArchaicFix are probably your best bet here.

**Comment by quentin452** [comment]
@MagmaBro123 maybe you could make a suggestion on the OptimizationsAndTweaks repo

**Comment by MagmaBro123** [comment]
> @MagmaBro123 maybe you could make a suggestion on the OptimizationsAndTweaks repo

Link?
