### ISSUE TITLE
travel.ogg plays on death when in the Nether

### ISSUE THREAD

**Issue by Roadhog360** [makamys/CoreTweaks#3]
Title, go to the Nether, then type /kill.

**Comment by anoomolu** [comment]
Can confirm this occurs, added CoreTweaks to my lightly modded pack and this sound plays after respawning from a nether death.

**Comment by makamys** [comment]
>Could this be fixed by checking the dead flag on the player?

Yep, that worked. The player gets revived during the handling of the respawn packet, and I had a hook right before that, so I was able to check there.
