### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Serega007RU** [makamys/CoreTweaks#4]
Hello, when I log on to the server, I have a crash
![image](https://user-images.githubusercontent.com/64780091/185741047-46fd0adb-5c69-4d26-9b2a-91731e00ef80.png)

What could be the problem? Here are the logs
[fml-client-latest.log](https://github.com/makamys/CoreTweaks/files/9386833/fml-client-latest.log)

This is all the information I can provide about the problem

**Comment by makamys** [comment]
This is caused by an error in the light fix stare's code. You can set `B:lightFixStare=false` as a workaround until it's fixed.
