### ISSUE TITLE
Some internal server hiccups with the latest version

### ISSUE THREAD

**Issue by Abalieno** [makamys/CoreTweaks#5]
Testing CoreTweaks-1.7.10-0.2.5-45-ge6dd0d8-dirty
compared to the newer CoreTweaks-1.7.10-0.2.6

Looking at F3 the internal server ms ticks shoot up for some reason when I immediately shift the view.

So for example I look in a certain direction, wait a few seconds, then immediately turn 180, the ms shoot up for a brief moment. It seems to happen erratically, but running a bunch of tests it seems it only happens with that new version.

EDIT: It actually happens even with small movements of the view. If I stay still the server is at 2ms, if I wait a few seconds and then move slightly the view then the internal server shoots up for an instant before settling back to 2ms. It's quite a weird behavior.

**Comment by Abalieno** [comment]
Ok, I figured it is related to the "B:lightFixStare=false" option.

Turning it off removes the weird hiccup on the internal server. Though I'm not sure it's working as intended if it creates that much overhead.

**Comment by makamys** [comment]
Good catch, thanks.
