### ISSUE TITLE
Black screen with Neodymium

### ISSUE THREAD

**Issue by Asek3** [makamys/CoreTweaks#9]
Just getting black screen on joining world with latest CoreTweaks and Neodymium.
![Screenshot_1](https://user-images.githubusercontent.com/64613894/210104987-8a3fab78-b050-41db-b00a-02b40fae91e7.png)

**Comment by Asek3** [comment]
![image](https://user-images.githubusercontent.com/64613894/210105245-5dd350c8-a37c-489c-8c79-d1e15041c133.png)
Oh, that's just problem with this mixin https://github.com/makamys/CoreTweaks/blob/master/src/main/java/makamys/coretweaks/mixin/optimization/ofupdaterendererreflect/MixinWorldRenderer.java

**Comment by makamys** [comment]
Disabling `of_optimize_world_renderer` in the config will disable that mixin, let me know if that fixes it.

**Comment by Asek3** [comment]
ofc helped
